version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - |
        STS="$( \
          aws sts assume-role \
          --role-arn "${DEPLOYMENT_ROLE_ARN}" \
          --role-session-name "${CODEBUILD_INITIATOR#*/}-${CODEBUILD_BUILD_NUMBER}" \
          --query "Credentials" \
          )"
      - aws configure set profile.zip-deployment.aws_access_key_id "$(jq -r '.AccessKeyId' <<<"${STS}")"
      - aws configure set profile.zip-deployment.aws_secret_access_key "$(jq -r '.SecretAccessKey' <<<"${STS}")"
      - aws configure set profile.zip-deployment.aws_session_token "$(jq -r '.SessionToken' <<<"${STS}")"
  build:
    commands:
      - |
        aws lambda update-function-code \
          --function-name ${LAMBDA_ARN} \
          --zip-file fileb://${LAMBDA_DEPLOYMENT_PACKAGE_NAME} \
          --publish \
          --profile zip-deployment
