version: 0.2

env:
  shell: bash
  variables:
    TF_CLI_ARGS: "-no-color"

phases:
  build:
    commands:
      - make lambda-ci
      - make fmt-check
      - ./scripts/run.sh plan development
      - ./scripts/run.sh plan production
