version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - make all-checks
      - time make tg-validate-development
      - time make tg-plan-development
      - time make tg-validate-production
      - time make tg-plan-production
      # - time scripts/run.sh validate-main development
      # - time scripts/run.sh plan development
      # - time scripts/run.sh plan production
